services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - goapp
  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: "postgres://<YOUR_CUSTOM_USERNAME>:<YOUR_CUSTOM_PASSWORD>@db:5432/<YOUR_CUSTOM_DATABASE_NAME>?sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: <YOUR_CUSTOM_USERNAME>
      POSTGRES_PASSWORD: <YOUR_CUSTOM_PASSWORD>
      POSTGRES_DB: <YOUR_CUSTOM_DATABASE_NAME>
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
